=== Evegen55/ForStudySpb/src/_java/_se/_09_XML/_task01/LibraryXMLSchema.xsd
<?xml version="1.0" encoding="UTF-8"?>
<schema targetNamespace="http://www.example.org/LibraryXMLSchema"
		elementFormDefault="qualified"
		xmlns="http://www.w3.org/2001/XMLSchema"
		xmlns:my="http://www.example.org/LibraryXMLSchema">


    <element name="library">
    	<complexType>
    		<sequence>
    			<element name="Book">
    				<complexType>
    					<sequence>
    						<element name="category" type="string"></element>
    						<element name="genre" type="string"></element>
    						<element name="title" type="string"></element>
    						<element name="author" type="string"></element>
    						<element name="year_of_publishing" type="int"></element>
    						<element name="year_of_getting" type="int"></element>
    						<element name="ISBN" type="string"></element>
    						<element name="price" type="double"></element>
    					</sequence>
    				</complexType>
    			</element>
    		</sequence>
    	</complexType>
    </element>
</schema>

=== Evegen55/ForStudySpb/src/_java/_se/_09_XML/_task01/LibraryByXMLSchemaWithXSI.xml
<?xml version="1.0" encoding="UTF-8"?>
<my:library xmlns:my="http://www.example.org/LibraryXMLSchema" 
xmlns:xsd="http://www.w3.org/2001/XMLSchema" 
xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" 
xsi:schemaLocation="http://www.example.org/LibraryXMLSchema LibraryXMLSchema.xsd ">
  <my:Book id="0">
    <my:category>my:category</my:category>
    <my:genre>my:genre</my:genre>
    <my:title>my:title</my:title>
    <my:author>my:author</my:author>
    <my:year_of_publishing>0</my:year_of_publishing>
    <my:year_of_getting>0</my:year_of_getting>
    <my:ISBN>my:ISBN</my:ISBN>
    <my:price>0.0</my:price>
  </my:Book>
</my:library>
